[phases.setup]
nixPkgs = [
  "python311Full",
  "curl",
  "cmake",
  "pkg-config",
  "gcc",
  "boost",
  "xorg.libX11",
  "xorg.libXext",
  "openblas"
]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip",
  "/opt/venv/bin/pip install cmake",
  "/opt/venv/bin/pip install dlib --no-cache-dir",
  "/opt/venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/python run.py"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
PYTHONUNBUFFERED = "1"
