[phases.setup]
nixPkgs = [
  "python311",
  "cmake", 
  "pkg-config",
  "gcc",
  "boost",
  "libx11",
  "libxext",
  "libopenblas"
]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "python -m pip install cmake",
  "python -m pip install dlib --no-cache-dir",
  "python -m pip install -r requirements.txt"
]

[start]
cmd = "python run.py"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
PYTHONUNBUFFERED = "1"
