[phases.setup]
nixPkgs = [
  "python311Full",
  "curl",
  "cmake",
  "pkg-config",
  "gcc",
  "boost",
  "xorg.libX11",
  "xorg.libXext",
  "openblas"
]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip wheel setuptools",
  "export CMAKE_ARGS='-DDLIB_NO_GUI_SUPPORT=ON'",
  "export DLIB_NO_GUI_SUPPORT=1",
  "/opt/venv/bin/pip install --no-cache-dir --timeout 1000 dlib",
  "/opt/venv/bin/pip install --no-cache-dir --timeout 1000 tensorflow-cpu",
  "/opt/venv/bin/pip install --no-cache-dir --timeout 1000 opencv-python-headless",
  "/opt/venv/bin/pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/python run.py"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
PYTHONUNBUFFERED = "1"
CMAKE_ARGS = "-DDLIB_NO_GUI_SUPPORT=ON"
DLIB_NO_GUI_SUPPORT = "1"
PIP_TIMEOUT = "1000"
PIP_DEFAULT_TIMEOUT = "1000"
# Model download timeouts
REQUESTS_TIMEOUT = "1200"
DOWNLOAD_TIMEOUT = "1200"
