[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "python -m pip install -r requirements.txt"]

[start]
cmd = "python run.py"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
PYTHONUNBUFFERED = "1"
