[phases.setup]
nixPkgs = [
  "python311Full",
  "curl",
  "cmake",
  "pkg-config",
  "gcc",
  "boost",
  "xorg.libX11",
  "xorg.libXext",
  "openblas"
]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip",
  "which cmake",
  "cmake --version",
  "export CMAKE_ARGS='-DDLIB_NO_GUI_SUPPORT=ON'",
  "/opt/venv/bin/pip install dlib --no-cache-dir --verbose",
  "/opt/venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/python run.py"

[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
PYTHONUNBUFFERED = "1"
CMAKE_ARGS = "-DDLIB_NO_GUI_SUPPORT=ON"
DLIB_NO_GUI_SUPPORT = "1"
